### ISSUE TITLE
Unable to handle exponential notational numbers

### ISSUE THREAD

**Issue by kfitzgerald** [schowdhuri/round-half-even#18]
in index.js: 
https://github.com/schowdhuri/round-half-even/blob/1b6d95485eb36521fd407106e4ec0e97d6147f58/src/index.js#L25

If an exponential number is passed e.g. `1e-8`, the strNum will be `"1e-8"`, which does not have a decimal and subsequently is unable to be rounded.

```
roundHalfEven(1e-8, 2);        // expected: 0.00, actual: 1e-8
roundHalfEven(0.000000010, 2); // expected: 0.00, actual: 1e-8
```

~~Might want to consider doing a value.toFixed(20) in there, to coerce it into decimal notation.~~ On second thought this will pre-round the value and most likely not work as intended.

**Comment by kfitzgerald** [comment]
Nice @rogersnick !

Since I was using [Decimal.js](https://mikemcl.github.io/decimal.js/#modes) for some other things, I ended up using that to handle rounding.

**Comment by schowdhuri** [comment]
Apologies for the delayed response, folks. I'm on vacation with very limited internet access.

@rogersnick Curious to know why you closed #21. Thanks for all the help!

**Comment by rogersnick** [comment]
Oh cool - I can open it back up. I was just clearing out my old pull requests and thought maybe this repo wasn't active. 

I'll take another quick gander because I think my implementation could be a little better.

**Comment by schowdhuri** [comment]
v1.3.0 includes the fix, thanks to @rogersnick! 🔥
